spring:
  application:
    name: address-service
    
  security:
    oauth2:
      resourceserver:
        jwt:
          # jwk-set-uri: http://auth-service/.well-known/jwks.json
          jwk-set-uri: http://localhost:9090/.well-known/jwks.json
server:
  port: 8084

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Distributed tracing and Zipkin
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  # Expose all actuator endpoints
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    # root: INFO                 # Root default
    # org.springframework: INFO   # Spring framework logs
    # org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.jmd.address: TRACE         # your package fully enabled

  pattern:
    level: "%5p [${spring.application.name:}, traceId=%X{traceId:-}, spanId=%X{spanId:-}]"
