spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**

        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/v1/categories/**

        - id: address-service
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/api/v1/addresses/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
            - Method=GET,POST,OPTIONS

      # # FINAL WORKING CORS CONFIG
      # globalcors:
      #   corsConfigurations:
      #     "[/**]":
      #       allowedOrigins:
      #         - "http://localhost:5173"
      #       allowedMethods:
      #         - GET
      #         - POST
      #         - PUT
      #         - DELETE
      #         - OPTIONS
      #       allowedHeaders: "*"
      #       allowCredentials: true
      #       maxAge: 3600
