# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/authservice
#     username: postgres
#     password: onkar
#     driver-class-name: org.postgresql.Driver

#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.PostgreSQLDialect



spring:
  application:
    name: auth-service

  # ===============================
  # DATABASE CONFIG
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/authservice
    username: postgres
    password: onkar
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ===============================
  # KAFKA CONFIG (PRODUCER + CONSUMER)
  # ===============================
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    consumer:
      group-id: role-events-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"


