spring:
  application:
    name: 'cart-service'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'

server:
  port: 8088

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    register-with-eureka: true
    fetch-registry: true
