spring:
  application:
    name: category-service
    
  security:
    oauth2:
      resourceserver:
        jwt:
          # jwk-set-uri: http://auth-service/.well-known/jwks.json
          jwk-set-uri: http://localhost:9090/.well-known/jwks.json

  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000        # 10 minutes
      cache-null-values: false
      key-prefix: "categoryService:"
      
server:
  port: 8082

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Distributed tracing and Zipkin
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  # Expose all actuator endpoints
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
    circuitbreakerevents:
      enabled: true

  health:
    circuitbreakers:
      enabled: true

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false

logging:
  pattern:
    level: "%5p [${spring.application.name:}, traceId=%X{traceId:-}, spanId=%X{spanId:-}]"


# --- Resilience4J Configuration for PRODUCT-SERVICE ---
resilience4j:

  # ================================
  # CIRCUIT BREAKER
  # ================================
  circuitbreaker:

    configs:
      default:
        registerHealthIndicator: true

        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5

        permittedNumberOfCallsInHalfOpenState: 3

        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s

        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true

        recordExceptions:
          - feign.FeignException
          - feign.RetryableException
          - java.io.IOException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - com.jmd.common.exception.ServiceException
          - com.jmd.common.exception.ServiceUnavailableException
          - com.jmd.common.exception.ClientNullException

        ignoreExceptions:
          - com.jmd.common.exception.BadRequestException
          - com.jmd.common.exception.ResourceNotFoundException
          - com.jmd.common.exception.AccessDeniedException
          - com.jmd.common.exception.ConflictException
          - com.jmd.common.exception.ValidateException

    instances:
      product-service-cb:
        baseConfig: default

  # ================================
  # RETRY
  # ================================
  retry:

    configs:
      default:
        maxAttempts: 3
        waitDuration: 2s

        retryExceptions:
          - feign.FeignException
          - feign.RetryableException
          - java.io.IOException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - com.jmd.common.exception.ServiceException
          - com.jmd.common.exception.ServiceUnavailableException
          - com.jmd.common.exception.ClientNullException

        ignoreExceptions:
          - com.jmd.common.exception.BadRequestException
          - com.jmd.common.exception.ResourceNotFoundException
          - com.jmd.common.exception.AccessDeniedException
          - com.jmd.common.exception.ConflictException
          - com.jmd.common.exception.ValidateException

    instances:
      product-service-retry:
        baseConfig: default

  # ================================
  # RATE LIMITER
  # ================================
  ratelimiter:

    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 1s

    instances:
      product-service-rl:
        baseConfig: default
