spring:
  application:
    name: inventory-service
    
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:9090/.well-known/jwks.json
          # jwk-set-uri: http://localhost:9090/.well-known/jwks.json


server:
  port: 8086

# Eureka configuration
eureka:
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka
      defaultZone: http://service-registry:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Distributed tracing and Zipkin
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      # endpoint: http://localhost:9411/api/v2/spans
      endpoint: http://zipkin:9411/api/v2/spans

  # Expose all actuator endpoints
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
    circuitbreakerevents:
      enabled: true

  health:
    circuitbreakers:
      enabled: true

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false

# -------------------------
# RESILIENCE4J
# -------------------------
resilience4j:

  # ================================
  # CIRCUIT BREAKER
  # ================================
  circuitbreaker:

    configs:
      default:
        registerHealthIndicator: true

        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5

        permittedNumberOfCallsInHalfOpenState: 3

        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s

        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true

        recordExceptions:
          - feign.FeignException
          - feign.RetryableException
          - java.io.IOException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - com.jmd.common.exception.ServiceException
          - com.jmd.common.exception.ServiceUnavailableException
          - com.jmd.common.exception.ClientNullException

        ignoreExceptions:
          - com.jmd.common.exception.BadRequestException
          - com.jmd.common.exception.ResourceNotFoundException
          - com.jmd.common.exception.AccessDeniedException
          - com.jmd.common.exception.ConflictException
          - com.jmd.common.exception.ValidateException

    instances:
      address-service-cb:
        baseConfig: default
      product-service-cb:
        baseConfig: default

  # ================================
  # RETRY
  # ================================
  retry:

    configs:
      default:
        maxAttempts: 3
        waitDuration: 2s

        retryExceptions:
          - feign.FeignException
          - feign.RetryableException
          - java.io.IOException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - com.jmd.common.exception.ServiceException
          - com.jmd.common.exception.ServiceUnavailableException
          - com.jmd.common.exception.ClientNullException

        ignoreExceptions:
          - com.jmd.common.exception.BadRequestException
          - com.jmd.common.exception.ResourceNotFoundException
          - com.jmd.common.exception.AccessDeniedException
          - com.jmd.common.exception.ConflictException
          - com.jmd.common.exception.ValidateException

    instances:
      address-service-retry:
        baseConfig: default
      product-service-retry:
        baseConfig: default

  # ================================
  # RATE LIMITER
  # ================================
  ratelimiter:

    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 1s

    instances:
      address-service-rl:
        baseConfig: default
      product-service-rl:
        baseConfig: default

# -------------------------
# LOGGING
# -------------------------
logging:
  level:
    com.jmd.inventory: DEBUG
    feign.Logger: DEBUG
    org.springframework.cloud.openfeign: INFO

  pattern:
    level: "%5p [${spring.application.name}, traceId=%X{traceId:-}, spanId=%X{spanId:-}]"
