# Database configuration
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/notification_service'
    username: 'root'
    password: 'onkar'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
