# Database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_service
    username: root
    password: onkar
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Twilio configuration (secured using environment variables)
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

  whatsapp:
    account-sid: ${TWILIO_WHATSAPP_ACCOUNT_SID}
    auth-token: ${TWILIO_WHATSAPP_AUTH_TOKEN}
    phone-number: ${TWILIO_WHATSAPP_PHONE_NUMBER}
