spring:
  application:
    name: product-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    openfeign:
      discovery:
        enabled: true
      circuitbreaker:
        enabled: true   # ✅ Enable Feign + Resilience4J integration

server:
  port: 8081

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Distributed Tracing + Zipkin
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  # Expose actuator endpoints
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# --- Feign Client Configuration ---
feign:
  httpclient:
    enabled: true      # ✅ Apache HTTP client enabled (production recommended)
  okhttp:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 5000          # ⏱️ 5 sec connection timeout
        readTimeout: 5000             # ⏱️ 5 sec read timeout
        errorDecoder: com.jmd.product.exception.FeignCustomErrorDecoder

# --- Resilience4J Configuration for INVENTORY-SERVICE ---
resilience4j:
  circuitbreaker:
    instances:
      INVENTORY-SERVICE:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true

        # ✅ Circuit breaker opens only for infra/network issues
        recordExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
          - feign.RetryableException
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException

        # ✅ Ignore business-level handled exceptions
        ignoreExceptions:
          - com.jmd.product.exception.DatabaseException
          - com.jmd.product.exception.ServiceException
          - com.jmd.product.exception.ResourceNotFoundException
          - com.jmd.product.exception.ValidateException

  retry:
    instances:
      INVENTORY-SERVICE:
        maxAttempts: 3
        waitDuration: 2s

        retryExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
          - feign.RetryableException
          - org.springframework.web.client.ResourceAccessException

        ignoreExceptions:
          - com.jmd.product.exception.DatabaseException
          - com.jmd.product.exception.ServiceException
          - com.jmd.product.exception.ResourceNotFoundException
          - com.jmd.product.exception.ValidateException

  ratelimiter:
    instances:
      INVENTORY-SERVICE:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 1s


logging:
  level:
    com.jmd.product.feignclient.InventoryServiceClient: DEBUG
    feign.Logger: DEBUG
    org.springframework.cloud.openfeign: DEBUG

