spring:
  application:
    name: product-service
    
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service/.well-known/jwks.json



  cloud:
    openfeign:
      discovery:
        enabled: true
      circuitbreaker:
        enabled: false

server:
  port: 8081

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Distributed Tracing + Zipkin + Actuator
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
    circuitbreakerevents:
      enabled: true

  health:
    circuitbreakers:
      enabled: true

# Feign Configuration
feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  client:
    config:
      INVENTORY-SERVICE:
        connectTimeout: 10000
        readTimeout: 30000
        errorDecoder: com.jmd.product.exception.FeignCustomErrorDecoder

# Resilience4J Configuration
resilience4j:
  timelimiter:
    instances:
      inventory-service-tl:
        timeoutDuration: 30s

  circuitbreaker:
    instances:
      inventory-service-cb:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 25s
        waitDurationInOpenState: 40s
        automaticTransitionFromOpenToHalfOpenEnabled: true

        recordExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
          - java.net.ConnectException
          - java.net.UnknownHostException
          - feign.RetryableException
          - org.springframework.web.client.ResourceAccessException
          - feign.FeignException$ServiceUnavailable
          - feign.FeignException$InternalServerError
          - com.jmd.product.exception.DatabaseException
          - com.jmd.product.exception.ServiceException

        ignoreExceptions:
          - com.jmd.product.exception.ResourceNotFoundException
          - com.jmd.product.exception.ValidateException

  retry:
    instances:
      inventory-service-retry:
        maxAttempts: 3
        waitDuration: 5s

        retryExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
          - java.net.ConnectException
          - feign.RetryableException
          - org.springframework.web.client.ResourceAccessException

        ignoreExceptions:
          - com.jmd.product.exception.ResourceNotFoundException
          - com.jmd.product.exception.ValidateException

  ratelimiter:
    instances:
      inventory-service-rl:
        limitForPeriod: 50
        limitRefreshPeriod: 1s
        timeoutDuration: 0   # fail fast


logging:
  level:
    com.jmd.product.feignclient.InventoryServiceClient: DEBUG
    feign.Logger: DEBUG
    org.springframework.cloud.openfeign: DEBUG
