# Database configuration
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/product_service'
    username: 'postgres'
    password: 'onkar'
    driver-class-name: 'org.postgresql.Driver'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
