spring:
  redis:
    host: ${SPRING_REDIS_HOST:redis-cache}
    port: ${SPRING_REDIS_PORT:6379}
  datasource:
    #url: jdbc:mysql://localhost:3306/user_service
    #url: jdbc:mysql://mysql-container:3306/user_service
    url: jdbc:mysql://mysql-db:3306/user_service?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: onkar
    driver-class-name: com.mysql.cj.jdbc.Driver
