spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # ----- Redis configuration -----
  redis:
    host: redis          # Docker service name
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000        # 10 minutes
      cache-null-values: false
      key-prefix: "userService:"

server:
  port: 8080

# --- Eureka configuration ---
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# --- Distributed tracing, Zipkin, and Actuator ---
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always

spring:
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0

# --- Logging with TraceId + SpanId ---
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.jmd.user: TRACE
  pattern:
    level: "%5p [${spring.application.name}, traceId=%X{traceId:-}, spanId=%X{spanId:-}]"

# --- Resilience4J Configuration ---
resilience4j:
  circuitbreaker:
    instances:
      USER-SERVICE:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
        ignoreExceptions:
          - com.jmd.user.exception.ResourceNotFoundException
          - com.jmd.user.exception.ResourceAlreadyExistsException

      ADDRESS-SERVICE:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - com.jmd.user.exception.AddressServiceUnavailableException
        ignoreExceptions:
          - com.jmd.user.exception.ResourceNotFoundException
          - com.jmd.user.exception.ResourceAlreadyExistsException

  retry:
    instances:
      USER-SERVICE:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException
        ignoreExceptions:
          - com.jmd.user.exception.ResourceNotFoundException
          - com.jmd.user.exception.ResourceAlreadyExistsException

      ADDRESS-SERVICE:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException
          - com.jmd.user.exception.AddressServiceUnavailableException
        ignoreExceptions:
          - com.jmd.user.exception.ResourceNotFoundException
          - com.jmd.user.exception.ResourceAlreadyExistsException

  ratelimiter:
    instances:
      USER-SERVICE:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 1s

      ADDRESS-SERVICE:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 1s
